"""Unit tests for output/report.py — fixed-code writing, banners, JSON+SARIF combos."""

from __future__ import annotations

import json
from pathlib import Path

from iac_scanner.models import Finding, FindingSource, Severity
from iac_scanner.orchestration.runner import PipelineResult
from iac_scanner.output.report import (
    _ensure_banner,
    _parse_fixed_files,
    _split_by_scan_headers,
    write_report_and_fixes,
)
from iac_scanner.scanners.base import ScanResult


class TestParseFixedFiles:
    def test_single_block_without_header_yields_one_anonymous_entry(self) -> None:
        out = _parse_fixed_files('resource "aws_s3_bucket" "b" {}\n')
        assert out == [("", 'resource "aws_s3_bucket" "b" {}')]

    def test_file_markers_are_split(self) -> None:
        fixed = (
            "---FILE: main.tf---\n"
            'resource "aws_s3_bucket" "b" {}\n'
            "\n"
            "---FILE: lib/extra.tf---\n"
            'resource "aws_iam_role" "r" {}\n'
        )
        out = _parse_fixed_files(fixed)
        assert len(out) == 2
        assert out[0][0] == "main.tf"
        assert "aws_s3_bucket" in out[0][1]
        assert out[1][0] == "lib/extra.tf"
        assert "aws_iam_role" in out[1][1]


class TestSplitByScanHeaders:
    def test_cdk_section_headers(self, tmp_path: Path) -> None:
        base = tmp_path / "cdk-app"
        base.mkdir()
        (base / "index.ts").write_text("// entry")
        (base / "lib").mkdir()
        (base / "lib" / "demo-stack.ts").write_text("// stack")
        fixed = (
            "// --- index.ts ---\n"
            "export const app = new cdk.App();\n"
            "// --- demo-stack.ts ---\n"
            "export class DemoStack {}\n"
        )
        parts = _split_by_scan_headers(
            fixed,
            [str(base / "index.ts"), str(base / "lib" / "demo-stack.ts")],
            base,
            "cdk",
        )
        assert len(parts) == 2
        assert parts[0][0] == "index.ts"
        assert parts[1][0] == "lib/demo-stack.ts"

    def test_terraform_section_headers(self, tmp_path: Path) -> None:
        base = tmp_path / "tf-app"
        base.mkdir()
        (base / "main.tf").write_text("# main")
        (base / "variables.tf").write_text("# vars")
        fixed = '# --- main.tf ---\nresource "aws_s3_bucket" "b" {}\n# --- variables.tf ---\nvariable "region" {}\n'
        parts = _split_by_scan_headers(
            fixed,
            [str(base / "main.tf"), str(base / "variables.tf")],
            base,
            "terraform",
        )
        assert len(parts) == 2
        names = sorted(p[0] for p in parts)
        assert "main.tf" in names
        assert "variables.tf" in names

    def test_no_headers_returns_empty(self) -> None:
        assert _split_by_scan_headers("plain fixed code", [], Path("/"), "terraform") == []


class TestEnsureBanner:
    def test_adds_banner_for_cdk(self) -> None:
        out = _ensure_banner("export const app = new cdk.App();", "cdk")
        assert out.startswith("// AI-generated by iac-scanner")

    def test_adds_banner_for_terraform(self) -> None:
        out = _ensure_banner('resource "aws_s3_bucket" "b" {}', "terraform")
        assert out.startswith("# AI-generated by iac-scanner")

    def test_banner_is_idempotent(self) -> None:
        content = "# content"
        once = _ensure_banner(content, "terraform")
        twice = _ensure_banner(once, "terraform")
        assert once == twice


class TestWriteReportAndFixes:
    def _result(self, tmp_path: Path, fixed_code: str = "") -> PipelineResult:
        src = tmp_path / "src"
        src.mkdir()
        entry = src / "main.tf"
        entry.write_text('resource "aws_s3_bucket" "b" {}')
        scan_result = ScanResult(
            iac_type="terraform",
            entry_path=entry,
            raw_content="# --- main.tf ---\n...",
            metadata={"files": [str(entry)]},
        )
        return PipelineResult(
            scan_result=scan_result,
            findings=[
                Finding(
                    severity=Severity.HIGH,
                    title="S3 public",
                    description="ACL permits public read",
                    location="main.tf:1",
                    source=FindingSource.LLM,
                )
            ],
            findings_raw='[{"severity":"high","title":"S3 public"}]',
            fixed_code=fixed_code,
            provider="openai",
            analysis_model="gpt-4o-mini",
            fix_model="gpt-4o",
        )

    def test_json_format_writes_json_only(self, tmp_path: Path) -> None:
        result = self._result(tmp_path)
        out_dir = tmp_path / "out"
        written = write_report_and_fixes(result, out_dir, output_format="json")
        assert (out_dir / "scan-report.json").exists()
        assert not (out_dir / "scan-report.sarif").exists()
        assert len(written) == 1
        data = json.loads((out_dir / "scan-report.json").read_text())
        assert data["provider"] == "openai"
        assert data["analysis_model"] == "gpt-4o-mini"
        assert data["fix_model"] == "gpt-4o"

    def test_sarif_format_writes_sarif_only(self, tmp_path: Path) -> None:
        result = self._result(tmp_path)
        out_dir = tmp_path / "out"
        write_report_and_fixes(result, out_dir, output_format="sarif")
        assert (out_dir / "scan-report.sarif").exists()
        assert not (out_dir / "scan-report.json").exists()

    def test_both_format_writes_json_and_sarif(self, tmp_path: Path) -> None:
        result = self._result(tmp_path)
        out_dir = tmp_path / "out"
        written = write_report_and_fixes(result, out_dir, output_format="both")
        assert (out_dir / "scan-report.json").exists()
        assert (out_dir / "scan-report.sarif").exists()
        assert len(written) == 2

    def test_fix_file_gets_banner(self, tmp_path: Path) -> None:
        result = self._result(
            tmp_path,
            fixed_code='resource "aws_s3_bucket" "secure" {}',
        )
        out_dir = tmp_path / "out"
        write_report_and_fixes(result, out_dir, write_fixed=True)
        fix_files = list((out_dir / "fixed").rglob("*.tf"))
        assert fix_files, "fixed/*.tf should have been written"
        content = fix_files[0].read_text()
        assert content.startswith("# AI-generated by iac-scanner")

    def test_env_var_format_is_honored(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.setenv("IAC_OUTPUT_FORMAT", "sarif")
        result = self._result(tmp_path)
        out_dir = tmp_path / "out"
        write_report_and_fixes(result, out_dir)  # no output_format arg
        assert (out_dir / "scan-report.sarif").exists()
